chore: Move relevant fields to Cargo.toml of lib
This means that, from the root of the workspace, things like this work:
```bash
cargo run --example 7_write_raw_blocks
cargo run --example 8_read_raw_blocks
```

However, running other examples won't work, since they're not
explicitely defined:
```bash
$ cargo run --example 0a_write_rgba
warning: /home/vv/dev/oss/exrs/lib/exrs/Cargo.toml: unused manifest key: lib.plugin
error: no example target named `0a_write_rgba` in default-run packages
help: available example targets:
    7_write_raw_blocks
    8_read_raw_blocks
```